version: '3'
services:
  aspmj-app:
    build:
      dockerfile: Dockerfile
      context: .
    image: aspmj-app-image
    container_name: aspmj-app
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:mysql://aspmj-db:3306/aspmj_sorteio
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-admin}
      SPRING_PROFILE: prod

  aspmj-db:
      image: mysql
      container_name: aspmj-db
      ports:
        - 3307:3306
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-admin}
        MYSQL_DATABASE: aspmj_sorteio
      volumes:
        - aspmj-mysql:/var/lib/mysql

volumes:
  aspmj-mysql: