apiVersion: v1

kind: Service

metadata:
  name: aspmj-sorteio-service
  labels:
    app: aspmj-sorteio-service

spec:
  type: LoadBalancer

  ports:
  - name: http
    port: 80
    targetPort: 8080

  selector:
    app: aspmj-sorteio

  sessionAffinity: ClientIP
